# numpy using array()

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])


print(arr.dtype)

arr

int32


array([1, 2, 3, 4, 5])

In [2]:
from numpy import *

arr = array([1,2,3,4,5.])

print(arr.dtype)

arr

float64


array([1., 2., 3., 4., 5.])

In [3]:
arr = array([1.,2.,3.,4.,5.],int)

print(arr.dtype)

print('\n',arr)

int32

 [1 2 3 4 5]


# using linspace()

In [4]:
arr = linspace(1,15,5)

arr

array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [5]:
from numpy import *

arr = linspace(1,50,11)

arr
#for large value use "%.2f" %arr

array([ 1. ,  5.9, 10.8, 15.7, 20.6, 25.5, 30.4, 35.3, 40.2, 45.1, 50. ])

# using arange()

In [6]:
arr = arange(1,20,2)

arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [7]:
arr = arange(0,10,5)

arr

array([0, 5])

In [8]:
arr = arange(0,15,1)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# using logspace()

In [9]:
arr = logspace(1,15,9)

arr

array([1.00000000e+01, 5.62341325e+02, 3.16227766e+04, 1.77827941e+06,
       1.00000000e+08, 5.62341325e+09, 3.16227766e+11, 1.77827941e+13,
       1.00000000e+15])

In [10]:
arr[0]

10.0

In [11]:
arr[8]

1000000000000000.0

In [12]:
print('%.2f' %arr[1])

562.34


In [13]:
print('%.2f' %arr[8])

# from 10 power log 1 to 10  power log 15 and divided into 9 parts.

1000000000000000.00


# using zeros()

In [14]:
arr = zeros(5)

print(arr.dtype)
arr

# it splits into float format.

float64


array([0., 0., 0., 0., 0.])

In [15]:
arr = zeros(5,int)

print(arr.dtype)

arr

int32


array([0, 0, 0, 0, 0])

# using ones()

In [16]:
arr = ones(7)

print(arr.dtype)
arr

float64


array([1., 1., 1., 1., 1., 1., 1.])

In [17]:
arr = ones(7,int)

print(arr.dtype)
arr

int32


array([1, 1, 1, 1, 1, 1, 1])

In [18]:
arr = ones(2*2,int)

print(arr.dtype)

arr

int32


array([1, 1, 1, 1])

In [19]:
arr = ones(6,int)

arr = arr + 1

arr

array([2, 2, 2, 2, 2, 2])

In [20]:
arr = ones(10,int)

arr = arr + 2

arr  += 1

arr

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

# copying an array

In [21]:
from numpy import *

arr = array([1,2,3,4,5])

arr = arr + 2

arr

# we can Add the value to the array.

array([3, 4, 5, 6, 7])

In [22]:
arr1 = array([1,2,3,4,5])

arr2 = array([5,4,3,2,1])

arr3 = arr1 + arr2

arr3

array([6, 6, 6, 6, 6])

In [23]:
from numpy import *

arr = array([1,2,3,4,5])

print("cos(arr) :",cos(arr))

print("sin(arr) :",sin(arr))

print("tan(arr) :",tan(arr))

print("sqrt(arr) :",sqrt(arr))

print("log(arr) :",log(arr))

print("max(arr) :",max(arr))

print("min(arr) :",min(arr))

print("sort(arr) :",sort(arr))

print("Reverse sort(arr) :",sort(arr)[::-1])

print("unique(arr) :",unique(arr))

print("sum(arr) :",sum(arr))



cos(arr) : [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
sin(arr) : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
tan(arr) : [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
sqrt(arr) : [1.         1.41421356 1.73205081 2.         2.23606798]
log(arr) : [0.         0.69314718 1.09861229 1.38629436 1.60943791]
max(arr) : 5
min(arr) : 1
sort(arr) : [1 2 3 4 5]
Reverse sort(arr) : [5 4 3 2 1]
unique(arr) : [1 2 3 4 5]
sum(arr) : 15


In [24]:
from numpy import *

arr1 = array([1,2,3,4,5])

arr2 = array([6,1,2,4,3])

print(concatenate([arr1,arr2]))

[1 2 3 4 5 6 1 2 4 3]


# shallow copy

In [25]:
arr1 = array([1,2,3,4,5])

arr2 = arr1.view()

arr1[1] = 6

print(arr2)

print(arr1)

print(id(arr1))
 
print(id(arr2))

# we can uderstand by seeing output.

[1 6 3 4 5]
[1 6 3 4 5]
2390683493600
2390683581536


# Deep copy

In [26]:
arr1 = array([1,2,3,4,5])

arr2 = arr1.copy()

arr1[1] = 6

print(arr2)

print(arr1)

print(id(arr1))
 
print(id(arr2))


[1 2 3 4 5]
[1 6 3 4 5]
2390683415456
2390683632384


# multi - Dimension Array

#### 02-06-21

In [27]:
from numpy import *

arr = array([[1,2,3],
             [3,4,5]])


print("arr.dtype:" ,arr.dtype)

print("arr.shape:" ,arr.shape)

print("arr.size:" ,arr.size)

print("arr.ndim:" ,arr.ndim)

print("arr.min :" , arr.min())

print("arr.max :" , arr.max())



arr.dtype: int32
arr.shape: (2, 3)
arr.size: 6
arr.ndim: 2
arr.min : 1
arr.max : 5


In [28]:
from numpy import *

arr = array([[1,2,3],
             [3,4,5]])



arr1 = arr.flatten()



print(arr)

print('\n\n  arr1 :',arr1)







[[1 2 3]
 [3 4 5]]


  arr1 : [1 2 3 3 4 5]


In [29]:
arr = array([[1,2,3,4,5,6],
            [6,5,4,3,2,1]])



arr1 = arr.flatten()


arr2 = arr1.reshape(3,4)

arr3 = arr1.reshape(2,2,3)

print("arr2 :\n" ,arr2)

print("arr3 :\n" ,arr3)




arr2 :
 [[1 2 3 4]
 [5 6 6 5]
 [4 3 2 1]]
arr3 :
 [[[1 2 3]
  [4 5 6]]

 [[6 5 4]
  [3 2 1]]]


In [30]:
arr = array([[1,2,3],
            [4,5,6]])

m = matrix(arr)

print("arr :\t\n", arr)




arr :	
 [[1 2 3]
 [4 5 6]]


In [31]:
m = matrix('1,2,3 ; 4,5,6 ; 6,7,8')

m1 = matrix('1,2 ; 4,5 ; 6,7')

print(m)

print("\n")

print(m1)

print("\n")

print("diagonal(m) :" ,diagonal(m))

print("\n m.min :" , m.min())

print("\n m.max :" , m.max())

    

[[1 2 3]
 [4 5 6]
 [6 7 8]]


[[1 2]
 [4 5]
 [6 7]]


diagonal(m) : [1 5 8]

 m.min : 1

 m.max : 8


### Add and Subtract matrix -

In [32]:
m1 = matrix('1,2,3 ; 4,5 6; 7,8,9')

m2 = matrix('3,2,1 ; 6,5,4 ; 9,8,7')

m3 = m1 + m2

m4 = m1 - m2

print("m3 :\n",m3)

print("\n")

print("m4 : \n",m4)

m3 :
 [[ 4  4  4]
 [10 10 10]
 [16 16 16]]


m4 : 
 [[-2  0  2]
 [-2  0  2]
 [-2  0  2]]


### Division and multiplication -

In [33]:
m1 = matrix('1,2,3 ; 4,5 6; 7,8,9')

m2 = matrix('3,2,1 ; 6,5,4 ; 9,8,7')

m3 = m1 / m2

m4 = m1 * m2

print("division of matrix : \n",m3)

print("\n")

print("Multiplication of matrix : \n",m4)



division of matrix : 
 [[0.33333333 1.         3.        ]
 [0.66666667 1.         1.5       ]
 [0.77777778 1.         1.28571429]]


Multiplication of matrix : 
 [[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]


## Functions -

In [34]:
def greeting():
    print("Hello")
    print("**Good Morning**")
    
    
greeting()

Hello
**Good Morning**


In [35]:
def sum(x,y):
    z = x + y
    print(z)
    
sum(11,22)

#print the value of sum.

33


In [36]:
def sum(x,y):
    z = x + y
    return z

result = sum(22,44)

print(result)

#return : return the value of sum.

66


In [37]:
def sum_subtract (x,y):
    a = x + y 
    b = x - y
    return(a,b)

result1, result2 = sum_subtract(22,11)

result  = sum_subtract(300,200)

print(result1,result2)

print("\n")
print(result)


33 11


(500, 100)


# string , tuples are immutable -
## so it's work on list -

In [38]:
 def update(lst):
        print(id(lst))
        
        lst[1] = 25
        
        print(id(lst))
        
        print("x ",lst)

lst = [10,20,30,40]

print(id(lst))

update(lst)

print("lst ",lst)


2390683519360
2390683519360
2390683519360
x  [10, 25, 30, 40]
lst  [10, 25, 30, 40]


# Types of Argument -

### Two types of Arguments:
    1)Formal Argument
    2)Actual Argument

In [39]:
def sum(x,y):      # here  x,y is formal Argument.
    z = x  + y
    print(z)
    
sum(11,22)         # here 11,22 is Actual Argument.

33


## Formal Argument -
    1)Position
    2)Default
    3)KeyWord
    4)Variable Length

In [40]:
def person(name,age):
    print(name)
    print(age)
    
person('Uday',21)  # Position Type.

Uday
21


In [41]:
def person(name,age = 20):
    print(name)
    print(age)
    
person('Uday')

print("\n")

person('Sai',19)      # Default Type.


Uday
20


Sai
19


In [42]:
def person(name,age):
    print(name)
    print(age)
    
person(age = 21 ,name = 'Uday')    # Keyword Type.

Uday
21


In [43]:
def sum(x , *y):
    z = x
    for i in y:
        z = z + i
    print(z)
    
sum(11,22,33,44,55)
                         #  Variable Lenght Type.

165


In [44]:
def sum (*y):
    z = 0
    for i in y:
        z = z + i
    print(z)
    
sum(11,22,33,44,55)

165


In [45]:
def person(name ,**data):
    
    print(name)
    
    for i , j in data.items():
        
        print(i,j)
     
    
person('Uday',age = 21,city = 'Anantapur',phno = 8008139871)

Uday
age 21
city Anantapur
phno 8008139871


# Global Variable -

In [46]:
x = 10
def something():
    x = 20
    print(x)

something()

print("out :",x)

20
out : 10


In [47]:
x = 100
def something():
    global x 
    x = 20
    print(id(x))
    print("inside :",x)

something()

print(id(x))
print("out :",x)
            # global  is used to local variable as Global.
            # Address also don't change after declartion.

140713568643456
inside : 20
140713568643456
out : 20


In [48]:
a = 100
print(id(a))

def something():
    a = 200
    
    x = globals()['a']
    print(id(a))
    print("inside :",a)
    
something()

print("out :",a)
    

140713568646016
140713568649216
inside : 200
out : 100


In [49]:
a = 100
print(id(a))

def something():
    a = 200
    
    x = globals()['a']
    print(id(a))
    
    globals()['a'] = 300
    print("inside :",a)
    
something()

print("out :",a)

140713568646016
140713568649216
inside : 200
out : 300


In [50]:
a = 100
print(id(a))

def something():
    a = 200
    
    x = globals()['a']
    print(id(a))
    print("inside :",a)
    
    globals()['a'] = 300

    
something()

print("out :",a)

140713568646016
140713568649216
inside : 200
out : 300


# Pass list to functions -

### Input to a list :-

In [16]:
lst = []

num = int(input("Enter the no of Elements :\t"))

for i in range(num):
    ele = int(input())
    lst.append(ele)

print(lst)


Enter the no of Elements :	5
1
5
4
5
7
[1, 5, 4, 5, 7]


In [ ]:
def count(lst):
    even = 0
    odd = 0
    for i in lst:
            if i % 2 == 0 :
                even += 1
                print("Even are :",i)
            else:
                odd += 1
                print("Odd are :",i)
                
    print("Counts of Even is {} and Odd is {}".format(even,odd))



lst = []
num = int(input("Enter the no of Elements :\t"))

for i in range(0,num):
    ele = int(input())
    lst.append(ele)
lst

count(lst)




# Factoiral of number -

In [ ]:
def fact(num):
     f = 1
     for i in range(1,num+1):
        f = i*f
     print(f"Factoiral of {num} is {f}")
        
x = int(input("Enter the Number:\t"))

fact(x)
        

# Recurrsion -
- A function calling it self.

In [ ]:
import sys

sys.setrecursionlimit(200)

print(sys.getrecursionlimit())


i = 0
def greet():
    global i
    i +=1
    print("Hello",i)
    greet()
    
greet()

# Factorial using Recurrsion -

In [ ]:
def fact(num):
    if num == 0:
        return 1
    return(num * fact(num-1))
    
    
x = int(input("Enter the Number:\t"))    
result = fact(x)

print(result)

# Anonymous functions or Lambda -
- fuction without defining the name.
- it's also known as lambda functions or lambda expressions.

In [ ]:
f  = lambda x : x ** 2
f1 = lambda x : x ** 3

num = int(input("Enter the Number:\t"))

print(f"square of {num} is {f(5)}")
print(f"cube of {num} is {f1(num)}")

In [ ]:
sum = lambda x,y : x + y

num = 11,22

print(sum(11,22))

## Lambda used in filter -

In [53]:
nums = [9,8,7,4,5,6,1,1]

evens1 = list(filter(lambda n : n % 2 == 0,nums))

print(evens1)


#   Let's remove "list" from the global namespace
#          >>>>>>>     del list     <<<<<<<<<
# Since there is no "list" in the global namespace of the module,
# Python goes to a higher-level namespace to find the name.  Let's remove "list" from the global namespace'''

[8, 4, 6]


In [52]:
def is_even(n):
    return n % 2 == 0

num = [9,8,2,5,6,9,1,0]

evens = list(filter(is_even,num))

print(evens)

[8, 2, 6, 0]


## Lambda used in map -

In [5]:
def is_update(n):
    return n * 2

num = [6,5,4,1,2,7,2]

doubles = list(map(is_update,num))

doubles

[12, 10, 8, 2, 4, 14, 4]

In [7]:
doubles = list(map(lambda n : n * 3 ,num))

doubles  # here it is mulpticated by 3.

[18, 15, 12, 3, 6, 21, 6]

## Lambda used in Reduce -

In [9]:
from functools import *

In [10]:
from functools import reduce

In [17]:
def is_total(n1,n2):
    return n1 + n2

num = [9,1,2,5,4,6]

sums = reduce(is_total,num)

sums

27

In [18]:
sum1 = reduce(lambda x,y : x + y,num)

sum1

27

# Modules -
- "Modules are saved in form of text and saved in .py format... " 
- Modules which used variables,functions,class,ets...
- Modules are not bulit in ..
- Modules should be import to use them 

In [8]:
from cals import *
a = 50
b = 40

y = sum_(a,b)
 
y


90

# using" _-main-_ "

In [9]:
from test1 import *

def one():
    adds_()
    print("from one")
    
def two():
    print("from two")
    
def main():
    one()
    two()
  
main()


result of s1 
from one
from two


In [10]:
from cals import *

z = sum_(11,1)

print(greet())

print("\n")

print(z)


Hello


12


In [11]:
from test1 import *

In [12]:
adds_()

result of s1 
